services:
  zyzzybot:
    container_name: zyzzybot
    build:
      context: .
    restart: always
    command: python main.py
    networks:
      - zyzzy_net
    env_file:
      - .env
    volumes:
      - .:/zyzzybot
      - ./src/bot/logs:/src/bot/logs
    depends_on:
      - redis_


networks:
  nginx_net:
    driver: bridge
    external: true
