services:
  zyzzybot:
    container_name: zyzzybot
    build:
      context: .
    restart: always
    command: python main.py
    networks:
      - nginx_net
    env_file:
      - .env
    volumes:
      - .:/zyzzybot
      - ./src/bot/logs:/src/bot/logs


networks:
  nginx_net:
    driver: bridge
    external: true
